version: "3"

services:
    php:
        build:
            context: ./dockerfiles/php-apps
        image: thesis/containerized-apps/php-apps:latest
        volumes:
            - .:/vagrant
        expose: 
            - 9000

    nginx:
        build:
            context: ./dockerfiles/nginx
        image: thesis/containerized-apps/nginx:latest
        volumes:
            - .:/vagrant
        links: 
            - php
        ports:
            - 80:80
            - 443:443

networks:
    default:
        external:
            name: thesis
