  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus-data:/prometheus-data
    command: "--config.file=/config/prometheus-data/prometheus.yml"