scrape_configs:
  - job_name: 'prometheus'
      scrape_interval: 1s 
      static_configs:
        - targets: ['api:3000']
          labels:
            service: 'test-prom' 
            group: 'production' 